# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('classname', models.CharField(max_length=50)),
                ('krcode', models.CharField(max_length=10)),
                ('credit', models.CharField(max_length=5)),
                ('timeperweek', models.CharField(max_length=5)),
                ('prof', models.CharField(max_length=30)),
                ('classcode', models.CharField(max_length=10)),
                ('limitstud', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
    ]
