# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classitem',
            options={'managed': False},
        ),
    ]
