# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20170412_1240'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classitem',
            table='classitem',
        ),
    ]
